### ISSUE TITLE
MP#11 Tracking History API(Last five): CURD 

### ISSUE THREAD

**Issue by KunSu** [KunSu/CMPE272MarketPlace#11]

**Comment by jenniferhou762** [comment]
**DB schema**
```
CREATE TABLE histories (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
         userid INT NOT NULL,
         item VARCHAR(255) NOT NULL,
         created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
```

**POST**
url: /histories.php
body: {"item":"xxxxxx"}
response:
no session: redirected to login.
success: status 200 with an empty body.
error: status 200 with a db error.

**GET**
url:/histories.php
response:
no session: redirected to login.
success: {"histories":["qqq","ppp"]}
error: status 200 with a db error.
